# Generated by Django 2.1.2 on 2018-10-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Films.Comment'),
        ),
    ]
