# Generated by Django 2.1.1 on 2018-10-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='Jean-Kevin', max_length=50),
        ),
    ]
