# Generated by Django 2.1.2 on 2018-10-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
