# Generated by Django 2.1.2 on 2018-10-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_auto_20181012_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='Films.Actor'),
        ),
    ]
