# Generated by Django 2.1.2 on 2018-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_auto_20181015_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(null=True, to='Films.Comment'),
        ),
    ]
