# Generated by Django 2.1.2 on 2018-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0004_auto_20181015_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(to='Films.Comment'),
        ),
    ]
