# Generated by Django 2.1.2 on 2018-10-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0008_auto_20181015_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Films.Movie'),
        ),
    ]
