# Generated by Django 2.1.2 on 2018-10-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0009_auto_20181015_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='actor',
            new_name='movie',
        ),
    ]
