# Generated by Django 2.1.2 on 2018-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0013_auto_20181015_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='Films.Actor'),
        ),
    ]
