# Generated by Django 2.1.2 on 2018-12-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0014_auto_20181023_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
