# Generated by Django 2.1.2 on 2018-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0017_auto_20181016_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.ManyToManyField(to='Films.Comment'),
        ),
    ]
