# Generated by Django 2.1.2 on 2018-10-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0018_auto_20181016_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='comment',
            new_name='comments',
        ),
    ]
